# Generated by Django 4.2.5 on 2025-12-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_author_photo_url_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pdf_url',
            new_name='content_url',
        ),
    ]
