# Generated by Django 4.2.5 on 2025-12-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20251222_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pdf_url',
            new_name='content_url',
        ),
    ]
