# Generated by Django 5.2.9 on 2025-12-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_pdf_url_book_content_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
