# Generated by Django 5.2.9 on 2025-12-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('romance', 'Romance'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('mystery', 'Mystery'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('action', 'Action'), ('adventure', 'Adventure'), ('fantasy', 'Fantasy')], max_length=50, null=True),
        ),
    ]
