# Generated by Django 5.2.9 on 2025-12-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('mobi', 'MOBI'), ('txt', 'Text'), ('other', 'Other')], default='pdf', max_length=10),
        ),
    ]
