# Generated by Django 5.2.9 on 2026-03-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_bookreview_poemreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_poems', to='accounts.appuser'),
        ),
    ]
