# Generated by Django 5.2.9 on 2026-03-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_poem_is_approved_poem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='genre',
            field=models.CharField(choices=[('poetry', 'Poetry'), ('classical_poetry', 'Classical Poetry'), ('modern_poetry', 'Modern Poetry'), ('ghazal', 'Ghazal'), ('free_verse', 'Free Verse')], default='poetry', max_length=50),
        ),
    ]
