# Generated by Django 5.2.9 on 2026-03-22 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_poemcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('narrator', models.CharField(blank=True, help_text='Name of the narrator', max_length=150)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('biography', 'Biography'), ('self_help', 'Self Help'), ('business', 'Business'), ('history', 'History'), ('science', 'Science'), ('poetry', 'Poetry'), ('drama', 'Drama')], default='fiction', max_length=50)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('audio_url', models.URLField(help_text='URL to the audio file')),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('language', models.CharField(default='Hindi', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiobooks', to='accounts.author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller')], default='fiction', max_length=50)),
                ('language', models.CharField(default='Hindi', max_length=50)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('reading_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_stories', to='accounts.author')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='accounts.appuser')),
            ],
            options={
                'verbose_name_plural': 'Short Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('literature', 'Literature'), ('poetry_reading', 'Poetry Reading'), ('author_interview', 'Author Interview'), ('book_review', 'Book Review'), ('writing_tips', 'Writing Tips'), ('storytelling', 'Storytelling'), ('documentary', 'Documentary'), ('educational', 'Educational')], default='literature', max_length=50)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(help_text='URL to the video file or YouTube link')),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('language', models.CharField(default='Hindi', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='accounts.author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
