# Generated by Django 5.2.9 on 2026-03-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_audiobook_shortstory_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='shortstory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='audiobook',
            index=models.Index(fields=['-created_at', 'is_active'], name='accounts_au_created_67c6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='poem',
            index=models.Index(fields=['-created_at', 'is_active', 'is_approved'], name='accounts_po_created_0c4984_idx'),
        ),
        migrations.AddIndex(
            model_name='shortstory',
            index=models.Index(fields=['-created_at', 'is_active', 'is_approved'], name='accounts_sh_created_41d7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at', 'is_active'], name='accounts_vi_created_5d9c76_idx'),
        ),
    ]
