# Generated by Django 5.2.9 on 2026-04-02 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_audiobook_created_at_alter_book_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('book_cover', 'Book Cover'), ('author_photo', 'Author Photo'), ('illustration', 'Illustration'), ('artwork', 'Artwork'), ('calligraphy', 'Calligraphy'), ('manuscript', 'Manuscript'), ('historical', 'Historical'), ('cultural', 'Cultural'), ('other', 'Other')], default='other', max_length=50)),
                ('image_url', models.URLField(help_text='URL to the image file')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('language', models.CharField(default='Hindi', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='accounts.author')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'is_active'], name='accounts_im_created_ab21fd_idx')],
            },
        ),
    ]
