# Generated by Django 5.2.9 on 2026-04-12 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('poem', 'Poem'), ('story', 'Short Story'), ('audiobook', 'Audiobook'), ('video', 'Video'), ('image', 'Image')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id', '-created_at'], name='accounts_co_content_fbc700_idx'), models.Index(fields=['user', '-created_at'], name='accounts_co_user_id_2bd827_idx')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('poem', 'Poem'), ('story', 'Short Story'), ('audiobook', 'Audiobook'), ('video', 'Video'), ('image', 'Image')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='accounts_li_content_adc90b_idx'), models.Index(fields=['user', 'content_type'], name='accounts_li_user_id_f1ebb6_idx')],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
    ]
