# Generated by Django 5.2.9 on 2026-04-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='description',
            field=models.TextField(blank=True, help_text='Short description or summary of the poem', null=True),
        ),
    ]
