# Generated by Django 5.2.9 on 2026-05-10 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_poem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('biography', 'Biography'), ('self_help', 'Self Help'), ('business', 'Business'), ('history', 'History'), ('science', 'Science'), ('poetry', 'Poetry'), ('drama', 'Drama')], db_index=True, default='fiction', max_length=50),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('romance', 'Romance'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('mystery', 'Mystery'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('action', 'Action'), ('adventure', 'Adventure'), ('fantasy', 'Fantasy')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('book', 'Book'), ('poem', 'Poem'), ('story', 'Short Story'), ('audiobook', 'Audiobook'), ('video', 'Video'), ('image', 'Image')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('book_cover', 'Book Cover'), ('author_photo', 'Author Photo'), ('illustration', 'Illustration'), ('artwork', 'Artwork'), ('calligraphy', 'Calligraphy'), ('manuscript', 'Manuscript'), ('historical', 'Historical'), ('cultural', 'Cultural'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='like',
            name='content_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.CharField(choices=[('book', 'Book'), ('poem', 'Poem'), ('story', 'Short Story'), ('audiobook', 'Audiobook'), ('video', 'Video'), ('image', 'Image')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='poem',
            name='category',
            field=models.CharField(blank=True, choices=[('love', 'प्रेम कविता'), ('nature', 'प्रकृति'), ('patriotic', 'देशभक्ति'), ('spiritual', 'आध्यात्मिक'), ('social', 'सामाजिक'), ('motivational', 'प्रेरणादायक'), ('sad', 'दुःख'), ('funny', 'हास्य')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='genre',
            field=models.CharField(choices=[('poetry', 'Poetry'), ('classical_poetry', 'Classical Poetry'), ('modern_poetry', 'Modern Poetry'), ('ghazal', 'Ghazal'), ('free_verse', 'Free Verse')], db_index=True, default='poetry', max_length=50),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shortstory',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller')], db_index=True, default='fiction', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortstory',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('literature', 'Literature'), ('poetry_reading', 'Poetry Reading'), ('author_interview', 'Author Interview'), ('book_review', 'Book Review'), ('writing_tips', 'Writing Tips'), ('storytelling', 'Storytelling'), ('documentary', 'Documentary'), ('educational', 'Educational')], db_index=True, default='literature', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['is_admin', '-created_at'], name='accounts_ap_is_admi_f8e53c_idx'),
        ),
        migrations.AddIndex(
            model_name='audiobook',
            index=models.Index(fields=['genre', 'is_active', '-created_at'], name='accounts_au_genre_f99770_idx'),
        ),
        migrations.AddIndex(
            model_name='audiobook',
            index=models.Index(fields=['title'], name='accounts_au_title_a08759_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='accounts_au_name_f98974_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_active', '-created_at'], name='accounts_bo_is_acti_44d0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre', 'is_active', '-created_at'], name='accounts_bo_genre_d0879c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category', 'is_active', '-created_at'], name='accounts_bo_categor_38649c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', 'is_active', '-created_at'], name='accounts_bo_author__820bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='accounts_bo_title_d5dabf_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['book', '-created_at'], name='accounts_bo_book_id_921817_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['user', '-created_at'], name='accounts_bo_user_id_65f3df_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'name'], name='accounts_ca_is_acti_06bb35_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'content_id'], name='accounts_co_content_ba7a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['category', 'is_active', '-created_at'], name='accounts_im_categor_a855a7_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['title'], name='accounts_im_title_efc5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['content_type', 'content_id', 'user'], name='accounts_li_content_1e76f6_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['email', 'is_used', '-created_at'], name='accounts_pa_email_0d7f07_idx'),
        ),
        migrations.AddIndex(
            model_name='poem',
            index=models.Index(fields=['category', 'is_active', 'is_approved', '-created_at'], name='accounts_po_categor_8803cf_idx'),
        ),
        migrations.AddIndex(
            model_name='poem',
            index=models.Index(fields=['genre', 'is_active', 'is_approved', '-created_at'], name='accounts_po_genre_492000_idx'),
        ),
        migrations.AddIndex(
            model_name='poem',
            index=models.Index(fields=['user', 'is_active', '-created_at'], name='accounts_po_user_id_bc3fef_idx'),
        ),
        migrations.AddIndex(
            model_name='poem',
            index=models.Index(fields=['title'], name='accounts_po_title_8f2789_idx'),
        ),
        migrations.AddIndex(
            model_name='poemreview',
            index=models.Index(fields=['poem', '-created_at'], name='accounts_po_poem_id_cae1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='poemreview',
            index=models.Index(fields=['user', '-created_at'], name='accounts_po_user_id_2539cd_idx'),
        ),
        migrations.AddIndex(
            model_name='shortstory',
            index=models.Index(fields=['genre', 'is_active', 'is_approved', '-created_at'], name='accounts_sh_genre_4d6bce_idx'),
        ),
        migrations.AddIndex(
            model_name='shortstory',
            index=models.Index(fields=['user', 'is_active', '-created_at'], name='accounts_sh_user_id_4e81e9_idx'),
        ),
        migrations.AddIndex(
            model_name='shortstory',
            index=models.Index(fields=['title'], name='accounts_sh_title_3ca1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category', 'is_active', '-created_at'], name='accounts_vi_categor_4f1dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title'], name='accounts_vi_title_c2a8df_idx'),
        ),
    ]
