# Generated by Django 5.2.9 on 2026-05-10 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_author_created_at_alter_appuser_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('poem', 'Poem'), ('story', 'Short Story'), ('audiobook', 'Audiobook'), ('video', 'Video'), ('image', 'Image')], db_index=True, max_length=20)),
                ('content_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='accounts_bo_content_17f400_idx'), models.Index(fields=['user', 'content_type'], name='accounts_bo_user_id_f36c5c_idx'), models.Index(fields=['user', '-created_at'], name='accounts_bo_user_id_bc6916_idx')],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
    ]
