# Generated by Django 5.2.9 on 2026-05-10 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_bookmark_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Story background image')),
                ('caption', models.TextField(blank=True, help_text='Text overlay on story')),
                ('background_color', models.CharField(blank=True, default='#FF7700', help_text='Background color hex if no image', max_length=20)),
                ('text_color', models.CharField(blank=True, default='#FFFFFF', max_length=20)),
                ('font_style', models.CharField(blank=True, default='normal', help_text='normal, bold, italic, serif', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='accounts.appuser')),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewed_stories', to='accounts.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_st_user_id_ab37ba_idx'), models.Index(fields=['is_active', '-created_at'], name='accounts_st_is_acti_61701e_idx'), models.Index(fields=['expires_at'], name='accounts_st_expires_0333d9_idx')],
            },
        ),
    ]
