# Generated by Django 5.2.9 on 2026-05-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_story_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True, help_text='Story background image (optional)', null=True),
        ),
    ]
